#Grid config:
rows: 22
cols: 10
block_size: 30

#UI config
fps: 120
delay: 0.05
drop_interval: 500

#Environment config
generator: 'random'    #'classic' / 'random'
seed: 123

#Agent config
strategy: 'promax'      #'normal' / 'promax'

#Color config
background: [245, 245, 245]
border: [50, 50, 50]
border_w: 1
grid: [220, 220, 220]
grid_w: 1
panel: [200, 200, 200]
text: [50, 50, 50]
button_bg: [200, 200, 200]
button_hover: [100, 100, 100]
